Refactoring code
Mezherman/FEM3-FINAL-PROJECT pull request #131
Opened 2020-02-09 17:22 UTC by pliushch

2020-02-10 08:55 UTC, Mezherman requested changes
Test

2020-02-10 08:55 UTC, Mezherman commented on client/src/components/About-us/about-us.js
Test in code

2020-02-10 21:45 UTC, shpakylia requested changes

2020-02-10 21:45 UTC, shpakylia commented on client/src/components/About-us/about-us.js
> +      <div className={classes.wrapper}>
не надо столько кода в одном файле. Вынеси смысловые компоненты в отдельный

2020-02-10 21:45 UTC, shpakylia commented on client/src/components/Catalog/catalog.js
> +  const filterRender = (desktop) => {
фильтр - 100% отдельный компонент со своими стейтами

2020-02-10 21:45 UTC, shpakylia commented on client/src/components/Contacts/contacts.js
> +    <Container maxWidth="xl" className={classes.minHeight}>
создай массивы телефонов и отмапь их

2020-02-10 21:45 UTC, shpakylia commented on client/src/components/Filter/Range/range.js
> +    setValue([filterResults.price[0], inputValue === '' ? '' : Number(inputValue)]);
на первый взгляд странно присваивать инпуту ' '. Но если так - то ок

2020-02-10 21:45 UTC, shpakylia commented on client/src/components/Footer/footer.js
> +  const logo = (
тоже лучше отдельным подкомпанентом в отдельном файле

2020-02-10 21:45 UTC, shpakylia commented on client/src/components/Search/search.js
> +  const renderSearch = (desktop) => {
ну можно проверку перед ретурн сделать, а сюда уже результат, но думаю, что не критично

2020-02-10 21:45 UTC, shpakylia commented on client/src/redux/actions/actionTypes.js
> +export const FETCH_TOP_PRODUCTS_LIST_REQUEST = 'FETCH_TOP_PRODUCTS_LIST_REQUEST'
это очень круто) Красавчик!

2020-02-11 09:20 UTC, shpakylia approved these changes

2020-02-11 09:27 UTC, Mezherman approved these changes

2020-02-11 09:27 UTC, merged